---
title: "Pretty Volcano"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(devtools)
library(gplots)
library(ggplot2)
library(EnhancedVolcano)
library(ggfortify)

theme<-theme(panel.background = element_blank(),
             panel.border=element_rect(fill=NA),
             # panel.grid.major = element_line(colour="grey90", size=0.5),
             # panel.grid.minor = element_blank(),
             strip.background=element_blank(),
             axis.title = element_text(colour="black", face="bold"),
             axis.text=element_text(colour="black"),
             axis.ticks=element_line(colour="black"),
             plot.margin=unit(c(1,1,1,1),"line"),
             plot.title = element_text(hjust = 0.5))

```



```{r}
sham_gene_results <- read.csv("~/code/ballgown2/sham_gene_results.csv")

res_sh <- data.frame("ensembl_id" = sham_gene_results$id,
                     "gene_name" = sham_gene_results$gene_name,
                     "log2fc" = -log2(sham_gene_results$fc), # needed to multiply by -1 to get right up/down orientation in volcano plot
                     "pvalue" = sham_gene_results$pval,
                     "qvalue" = sham_gene_results$qval,
                     "significance" = ifelse(sham_gene_results$qval < 0.05, "FDR < 0.05", "Not Significant"))



```

```{r}
# using enhancedvolcano package
EnhancedVolcano(res_sh, lab="", x = "log2fc", y = "pvalue", xlim = c(-4,4), ylim=c(0,6), FCcutoff = 1.5, transcriptPointSize = 1.5, transcriptLabSize = 3, col=c('black', 'red', 'black', 'red'), colAlpha = 1, legend = "", cutoffLineType = 'blank')
```



```{r}
# using ggplot2?

# create the subset to highlight genes of interest
goi <- c("Nnmt", "Mmaa", "Fgf21", "Pigr")
genes <- subset(res_sh, gene_name %in% goi)

volcano <- ggplot(res_sh, aes(x = log2fc, y = -log10(pvalue), color=significance)) +
  geom_point(alpha = 0.75) +
  scale_color_manual(values = c("red", "black")) +
  theme_bw(base_size = 12) + theme(legend.position = "bottom")  +
  geom_point(data=genes, colour="purple") +  # this adds a red point
  geom_label(data=genes, label=genes$gene_name, vjust=1.25, colour="purple")+ # goi text label
  xlab(expression('Log'['2']*' Fold Change'))+
  ylab(expression('-Log'['10']*italic('P')))+
  theme(legend.title=element_blank())
  
  


# add gene labels to significant genes:
# geom_text_repel(
#     data = subset(res_sh, qvalue < 0.05),
#     size = 3.5
#     box.padding = unit(0.35, "lines"),
#     point.padding = unit(0.3, "lines")

# plot the data
# ggplot(a, aes(log10(Index1+1), Index2)) + geom_point(alpha=1/5) +  # this is the base plot
#   geom_point(data=g1, colour="red") +  # this adds a red point
#   geom_text(data=g1, label="G1", vjust=1) # this adds a label for the red point

volcano
```



```{r}
# previous code

results_genes <- read.csv("~/code/ballgown2/sham_gene_results.csv")
i <- -1
file <- "Sham"
q <- 0.05
fch <- 1 


with(results_genes, plot(-log2(fc), -log10(pval), pch=20, main="Sham Volcano plot"), xlim=c(-10,10), ylim=c(0,11))

# Add colored points: orange if q value<q, green if log2FC>1.5, red if log2FC<-1.5, blue if both)
with(subset(results_genes, qval<q ), points(i*log2(fc), -log10(pval), pch=20, col="orange"))
with(subset(results_genes, i*log2(fc)> fch), points(i*log2(fc), -log10(pval), pch=20, col="green"))
with(subset(results_genes, i*log2(fc)< -fch), points(i*log2(fc), -log10(pval), pch=20, col="red"))
with(subset(results_genes, qval<q & abs(log2(fc))>fch), points(i*log2(fc), -log10(pval), pch=20, col="blue"))

# plot genes of interest (goi) with one command
goi <- c("Nnmt", "Mmaa", "Fgf21", "Pigr", "Tuba8")
goi_val <- filter(results_genes_sham, gene_name %in% goi)
with(goi_val, points(-log2(fc), -log10(pval), pch=20, col="purple"))
with(goi_val, textxy(-log2(fc), -log10(pval), labs=gene_name,col="purple",cex=.8))

# Add text saying how many up, down, and total DE genes were found
text(7, y=9, labels = paste("Up DE genes: ", nrow(genes_up)), cex = 0.9)
text(-7, y=9, labels = paste("Down DE genes: ", nrow(genes_down)), cex = 0.9)
text(0, y=8, labels = paste("Total DE genes: ", nrow(results_genes)), cex = 0.9)

# Add labels
with(subset(results_genes, qval<.05 & abs(log2(fc))>1), textxy(-log2(fc), -log10(pval), labs=gene_name, cex=.8))

```

