---
title: "FPKM_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)

setwd("~/code/qPCR_FPKM")
```

Set-up colors
```{r colors, include = False}
green <- "#70AD46" # unaffecteds, no treatment
yellow <- "#FBBF07" # unaffecteds, vanc
blue <- "#4370C3" # affecteds, no treatment
orange <- "#ED7E2F" # affecteds, vanc
colors <- c(green, yellow, blue, orange)
```

Load data:
```{r}
all_gexpr <- read.csv("all_gexpr_unfiltered.tsv", sep = "\t")
all_gexpr <- tibble::rownames_to_column(all_gexpr, var = "ensembl_id")
all_gexpr
```

```{r}
# label gene names for each ensebl Ids to make sorting easier
load("~/code/qPCR_FPKM/FullconversionList.Rda") # Loads dataframe called conversionList
labeledDF <- left_join(all_gexpr, FullConversionList, by = c("ensembl_id" = "ensembl_gene_id"))
relabeledDF <- labeledDF %>% select(external_gene_name, everything()) %>% slice(4:nrow(labeledDF))
relabeledDF
```
```{r}
# select genes of itnerest
gois <- c("Nnmt", "Nampt", "Nmnat1", "Nmnat2", "Nmnat3", "Nmrk1", "Nmrk2", "Sirt1", "Cd38", "Pparg", "Mat1a", "Mat2a", "Mat2b", "Amd1", "Gnmt", "Gamt", "Pemt", "Mtr", "Mtrr", "Bhmt", "Ahcy", "Cbs", "Aox1", "Aox2", "Cyp2e1", "Sirt2", "Sirt3", "Sirt4", "Sirt5", "Sirt6", "Sirt7", "Ppargc1a")

gois_FPKM <- relabeledDF %>% filter(external_gene_name %in% gois)

# following only works if no repeats in genes
gois_FPKM_T <- gois_FPKM %>% select(-ensembl_id) %>% 
  gather(sample_id, valname, -external_gene_name) %>% 
  spread(external_gene_name, valname)



# delete "FPKM." from sample_id
gois_FPKM_T$sample_id <- gsub("FPKM.", "", gois_FPKM_T$sample_id)
gois_FPKM_T
```
##NOTE: missing Nrk1 and Nrk2 for some reason???
###Changed Nrk to Nmrk - found Nmrk1 but not 2



```{r}
# put in long format so can loop in making graphs
gois_FPKM_long <- gois_FPKM_T %>% gather("gene", "FPKM", -sample_id)

# add pdata to data frame so can sort and graph more easily
pdata <- read.csv("Vanc_pdata.csv")

labeled_gois_FPKM <- left_join(gois_FPKM_long, pdata, by = "sample_id")
labeled_gois_FPKM
```
```{r}
# reorder and rename groups for plots
labeled_gois_FPKM$group <- ordered(labeled_gois_FPKM$group, levels = c("Un_Sham", "Un_Vanc", "Af_Sh", "Af_Vanc"))

```




Now to (finally) make bar graphs for all genes of interest:
```{r}

# calculate means and sd
Un_Sham = "Unaffecteds (+/-)\nNo Treatment\n(n=6)"
Un_Vanc = "Unaffecteds (+/-)\nVancomycin\n(n=6)"
Af_Sh = "Affecteds (-/-)\nNo Treatment\n(n=6)"
Af_Vanc = "Affecteds (-/-)\nVancomycin\n(n=6)"
my_comparisons <- list( c(Un_Sham, Af_Sh), c(Af_Sh, Af_Vanc), c(Un_Sham, Un_Vanc))


for (i in seq_along(gois)) {

  plot <- ggplot(filter(labeled_gois_FPKM, gene == gois[i]), aes(x=group, y = FPKM, fill=group)) +
    stat_summary(geom = "bar", fun.y = mean, position = "dodge") +
    stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge", width = 0.2)  +
    stat_compare_means()+
    stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
    theme_classic()+
    scale_fill_manual(values=colors) +
    ggtitle(gois[i]) +
    theme(plot.title = element_text(hjust = 0.5, size=24))

  ggsave(plot, file=paste("/Users/iskoec/code/qPCR_FPKM/pics/", gois[i], "_FPKM.tiff", sep=""))
  
  }

```

```{r}
# calculate means and sd
Un_Sham = "Unaffecteds (+/-)\nNo Treatment\n(n=6)"
Un_Vanc = "Unaffecteds (+/-)\nVancomycin\n(n=6)"
Af_Sh = "Affecteds (-/-)\nNo Treatment\n(n=6)"
Af_Vanc = "Affecteds (-/-)\nVancomycin\n(n=6)"
my_comparisons <- list( c(Un_Sham, Af_Sh), c(Af_Sh, Af_Vanc), c(Un_Sham, Un_Vanc))

plot <- ggplot(filter(labeled_gois_FPKM, gene == "Nnmt"), aes(x=group, y = FPKM, fill=group)) +
    stat_summary(geom = "bar", fun.y = mean, position = "dodge") +
    stat_summary(geom = "errorbar", fun.data = mean_se, position = "dodge", width = 0.2)  +
    stat_compare_means()+ # global p value
    stat_compare_means(label = "p.signif", method = "t.test", ref.group = Un_Sham, label.y = 60) +                 # Pairwise comparison against Unaffected, no treatment
    stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
    theme_classic()+
    scale_fill_manual(values=colors) +
    ggtitle("Nnmt") +
    theme(plot.title = element_text(hjust = 0.5, size=24))

plot
```

